### ISSUE TITLE
rubrics script stopped working

### ISSUE THREAD

**Issue by teatown** [jamesjonesmath/canvancement#12]
I'm using the Rubrics script with Firefox and Tampermonkey since 10/2017 without any issue.  Stopped working in the last week.  Noticed a red "notification" symbol on Tampermonkey but never actually found the notification.  Removed the script and reinstalled but no luck.  I do see all the features (points box below the answer for example as you would expect with the script) but the box is non-functional.  If I put anything in the lower box and advance to next student the grade is not entered.  I've checked for an update but it says it is up-to-date.  My domain is: https://olympic.instructure.com. Thanks for any help you can offer.  I am lost without the script.

**Comment by jamesjonesmath** [comment]
When you say "rubric script", it sounds like you're actually talking about QuizWiz. If so, the duplicate header at the bottom is a known issue and I have a bug fix for that particular issue. The person who reported it also reported some other issues as well and I haven't had a chance to track those down. I didn't want to update and then come back in another day or two and update again, but given that classes start in 30 hours and I'm not ready yet, perhaps I should just publish it and see what else doesn't work.

Canvas went through and introduced some hidden fields to hold the actual value but left the other box there to input the value. The kept the identifier with the hidden one and the new one doesn't have an identifier. Hidden boxes don't trigger events when they change.

Was there anything besides the lower box not working? Other than entering a fudge point of 0 not working? That's a Canvas issue, btw, and they have updated their source code to fix it, but I don't know when it's going to become available.

The red notification on Tampermonkey isn't a notification that I know of, it's the number of scripts that are running on that page.

**Comment by jamesjonesmath** [comment]
I fixed the highlighting of answers when grading a question at a time. Canvas changed the name of the class from "short_answer_question" to "essay_question" and I wasn't looking for that. I added "essay_question" to the list of classes to look for and it worked.

I could have left it like that, but I decided to go ahead and do some more while I had it. I now look at the score for the equation and if it is already graded, then it sets the opacity to 50% so it's easy to tell which questions are completely missing a grade.

You may need to go into the Tampermonkey dashboard and update the script (by clicking on the value in the Last Updated column for that Canvancement). It's sufficiently different that it may ask you to verify the changes rather than making them automatically.

**Comment by teatown** [comment]
James,

Ungraded answers are still not highlighted for me.  I did as you said and clicked on the last updated column and it said 22 hours ago and wouldn't let me do anything else.  So, I uninstalled and reinstalled the rubrics script but no change.

just FYI.

Mirelle

Mirelle Cohen Ph.D.
I-BEST Coordinator
Coordinator of the Human Service & Chemical Dependency Professional Programs, Professor of Sociology
HSS344
Olympic College
1600 Chester Avenue
Bremerton, WA, 98337-1699
Tel: 360 475 7553
Fax: 253 503 3298
Email: mcohen@olympic.edu

________________________________

**Comment by teatown** [comment]
I think you updated the quizzes script but not the rubrics script because rubrics says updated 9 months ago on this page but quizzes says 4 hours ago?

https://github.com/jamesjonesmath/canvancement


Mirelle Cohen Ph.D.
I-BEST Coordinator
Coordinator of the Human Service & Chemical Dependency Professional Programs, Professor of Sociology
HSS344
Olympic College
1600 Chester Avenue
Bremerton, WA, 98337-1699
Tel: 360 475 7553
Fax: 253 503 3298
Email: mcohen@olympic.edu

________________________________

**Comment by teatown** [comment]
Just uninstalled "rubrics" and installed "speed enhancements" and still no luck on highlighting ungraded questions.  FYI.  I'll leave you alone now.

Mirelle Cohen Ph.D.
I-BEST Coordinator
Coordinator of the Human Service & Chemical Dependency Professional Programs, Professor of Sociology
HSS344
Olympic College
1600 Chester Avenue
Bremerton, WA, 98337-1699
Tel: 360 475 7553
Fax: 253 503 3298
Email: mcohen@olympic.edu

________________________________
