### ISSUE TITLE
Sort a Rubric

### ISSUE THREAD

**Issue by rebeccaongmtu** [jamesjonesmath/canvancement#17]
Your sort-rubric.user.js is no longer working in Tampermonkey. The JS still loads in Tampermonkey when I go to the rubric page, I just can't drag anything. 

Tampermonkey shows two errors in the JS:
Line 10 - 'waitForKeyElements' is not defined
Line 12 - '$' is not defined

I saw the $ problem in the other issue that is posted about QuizWhiz, but there wasn't enough info there for me to figure out how to fix it.

**Comment by jamesjonesmath** [comment]
Thanks. There’s a lot of stuff broken right today and I’m working on them. I’ve finished QuizWiz, Obtaining an Access Report, and am close to finishing the Roster Sorter. I’ll add the rubric sorter to the list to look at.

**Comment by jamesjonesmath** [comment]
This should be fixed now. I took the time to completely rewrite the code and bring it up to better programming practices.

I'm not going to close this just yet -- the jQuery issue is dependent upon you not being quick enough that you click the edit button before it's loaded. That's unlikely, but please test it and let me know if it works.

I also tightened up some of the checking on what pages it runs on and what it runs on, so hopefully I didn't break some behavior.

**Comment by rebeccaongmtu** [comment]
It's working! The $ is still showing as an error in the code, but that isn't impacting functionality. Thanks so much!
